import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.body}>
        <div className={styles.image}>
          <Image
            src={image1}
            alt="masahiro-miyagi-xk0-YHAn3dzk-unsplash"
            placeholder="blur"
            layout="fill"
          />
        </div>

        <div className={styles.image}>
          <Image
            src="https://i.ibb.co/LnmdGmq/masahiro-miyagi-xAn3dzk-unsplash-1.jpg"
            alt="masahiro-miyagi-xk0-YHAn3dzk-unsplash"
            placeholder="blur"
            blurDataURL={getBase64FromUrl(
              "https://i.ibb.co/LnmdGmq/masahiro-miyagi-xAn3dzk-unsplash-1.jpg"
            )}
            layout="fill"
          />
        </div>

        <div className={styles.image}>
          <Image
            src="https://i.ibb.co/gzSqzbb/blockchain.jpg"
            alt="masahiro-miyagi-xk0-YHAn3dzk-unsplash"
            placeholder="blur"
            blurDataURL={getBase64FromUrl(
              "https://i.ibb.co/gzSqzbb/blockchain.jpg"
            )}
            layout="fill"
          />
        </div>

        <div className={styles.image}>
          <Image
            src="https://i.ibb.co/SNyJ6bW/priscilla-du-preez-AOd-ELn6sen-M-unsplash-1.jpg"
            alt="masahiro-miyagi-xk0-YHAn3dzk-unsplash"
            placeholder="blur"
            blurDataURL={getBase64FromUrl(
              "https://i.ibb.co/SNyJ6bW/priscilla-du-preez-AOd-ELn6sen-M-unsplash-1.jpg"
            )}
            layout="fill"
          />
        </div>

        <div className={styles.image}>
          <Image
            src="https://i.ibb.co/d4ns3HW/dad-hotel-P6-B7y6-Gnyzw-unsplash.jpg"
            alt="masahiro-miyagi-xk0-YHAn3dzk-unsplash"
            placeholder="blur"
            blurDataURL={getBase64FromUrl(
              "https://i.ibb.co/d4ns3HW/dad-hotel-P6-B7y6-Gnyzw-unsplash.jpg"
            )}
            layout="fill"
          />
        </div>

        <div className={styles.image}>
          <Image
            src="https://i.ibb.co/LnmdGmq/masahiro-miyagi-xAn3dzk-unsplash.jpg"
            alt="masahiro-miyagi-xk0-YHAn3dzk-unsplash"
            placeholder="blur"
            blurDataURL={getBase64FromUrl(
              "https://i.ibb.co/LnmdGmq/masahiro-miyagi-xAn3dzk-unsplash.jpg"
            )}
            layout="fill"
          />
        </div>
      </div>
    </div>
  );
}
